#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$PLUGIN_CORE_AVAILABLE_PATH/config/functions"

pre-release-dockerfile() {
  local APP="$1"; verify_app_name "$APP"
  local IMAGE_TAG="$2";

  DOKKU_IGNORE_DOCKERFILE_PORTS=$(config_get "$APP" DOKKU_IGNORE_DOCKERFILE_PORTS || true)

  if [[ -n "$DOKKU_IGNORE_DOCKERFILE_PORTS" ]]; then
    config_unset --no-restart "$APP" DOKKU_DOCKERFILE_PORTS
  fi
}

pre-release-dockerfile "$@"
